import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Data from "./data.json";
import StreetView from "./StreetView";
import Test from "./GuessMap";
import FullscreenMap from "./FullscreenMap";

export default function Home() {
  const [center, setCenter] = useState(
    Data[Math.floor(Math.random() * Data.length)]
  );

  const [markers, setMarkers] = useState([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <StreetView center={center} />
        <Test center={center} setParentMarkers={setMarkers} />
        {markers.length > 0 && <FullscreenMap markers={markers} />}
      </div>
    </>
  );
}
